### ISSUE TITLE
Possibility to esclude items from lazy

### ISSUE THREAD

**Issue by rcwd** [erikyo/f2ll#6]
Hello,
it should be a good idea to add a way to exclude some images to be lazyload.
For example by a default attribute  nolazy, or maybe by adding a specific css class (.nolazy) or css path (.#mydiv .mywrapper .mypic).

Thanks

**Comment by erikyo** [comment]
good catch, i'll try to fix asap! 

Since it is a common pattern I prefer the idea of the ".nolazy" class, which is also easy to implement

What is needed is to **not** apply the lazyload script when the Element has the given class. Basically a "return" here will do the job
https://github.com/erikyo/auto-lazyload/blob/30d45ad4dba3bb35388fabdfa0052f6c8ca8b008/src/locator.ts#L22-L24

**Comment by rcwd** [comment]
Your idea is right!
I opened a pull request about that :)

**Comment by rc-advertoo** [comment]
Thanks! Exclusions now work very well! You can close this issue.

**Comment by erikyo** [comment]
😉thanks for the feedback!

closed with #7
